### ISSUE TITLE
Windows 11 - Instant Crash when opening

### ISSUE THREAD

**Issue by Bloodmotionn** [teacat/chaturbate-dvr#10]
Hello ! 

Been trying to use the software, unfortunately, when I try to open it, a brief windows open and close immediately. 
Both as normal launch and admin launch

**Comment by mK33y** [comment]
go into the folder where you stuff is located, go into your adress bar in the folder and type "cmd" and hit enter. there you type in "chaturbate-dvr.exe -u USERNAME" without " and hit enter. for each user your doing this you wanna record.

**Comment by YamiOdymel** [comment]
Yea, as @mK33y said, you **don't** open the program with double click, you open it with a CMD or Terminal that looks like this

![Command_Prompt_on_Windows_10_RTM](https://user-images.githubusercontent.com/7308718/188749673-41db076c-68e0-446c-81da-b9d6442ff35d.png)

make sure you open the CMD/Terminal in the `/bin/windows` **folder**, and type the following command:

```
chaturbate-dvr.exe -u USERNAME
```

then you should see it working (sorry for the screenshot, I wasn't on an English language system):

![image](https://user-images.githubusercontent.com/7308718/188749786-378781db-8cc9-4e5d-9aca-5335f8329790.png)
