### ISSUE TITLE
Can't open on Win10 

### ISSUE THREAD

**Issue by sminato27** [teacat/chaturbate-dvr#14]
I've tried to execute the .exe file, tried to open in CMD, PowerShell and VSCode but nothing happens.

**Comment by YamiOdymel** [comment]
What command do you use? What is nothing? Check #10

**Comment by sminato27** [comment]
> What command do you use? What is nothing? Check #10 

Maybe I didn't execute it correctly. I'll try it again soon.

**Comment by YamiOdymel** [comment]
Sure, hope nothing will go wrong. If anything happended just remember to tell me the commands you use or maybe I will recompile it 🫠

**Comment by sminato27** [comment]
> Sure, hope nothing will go wrong. If anything happended just remember to tell me the commands you used or maybe I will recompile it 🫠

![image](https://user-images.githubusercontent.com/59450675/190027978-a98a790c-ecac-4ddc-9101-a10562a5e2d5.png)
I think I've started correctly but is it working normally? It's generating files and erasing them on "video" folder but they don't pass 1.045 KB. 
I've used this command: chaturbate-dvr.exe -u heatherbby9
Another question: How to stop it?
![image](https://user-images.githubusercontent.com/59450675/190028096-2aa79513-d5e2-47c6-9cfe-8466a58b9c5c.png)

**Comment by YamiOdymel** [comment]
Yea, It's working normally. Live streams are video segments, the Program downloads segments and merge them into the main file.

Windows updates the file information every few seconds, so you should be able to see the video in `heatherbby9_2022-09-13_20-35-09.ts` file soon, don't mind the other `~147.ts` segment files, they will be deleted by the program automatically.

To stop the program just close it, though the last few seconds might be lost (because it's not a "graceful shutdown").

**Comment by sminato27** [comment]
Thank u so much for ur help and ur work in this program, it's working good af. And don't hesitate adding a donation section if u need.

**Comment by YamiOdymel** [comment]
You can open multiple programs to record the different streams. 

The program will start recording once the channel is online. It checks the online status every minute by default.

If the channel went offline, it will also wait till the channel is online unless you stop the program.

**Comment by sminato27** [comment]
Hey, sry to reopen this thread but today I've rec a stream for about 30min and after finished I've started to watch it but it have a LOT of frame loss and many frames are in 2x speed. There's any thing that I can do to fix it?

**Comment by YamiOdymel** [comment]
oh- no, is your internet connection stable? The lost frames cannot be recovered, sorry 😭

maybe you can try another tool like https://github.com/lossless1024/StreaMonitor

**Comment by sminato27** [comment]
> oh- no, is your internet connection stable? The lost frames cannot be recovered, sorry 😭"
> 
> They don't store the segments for too long (preserved for few seconds only I think), hence it's impossible to fetch them back and fix it.
> 
> Maybe you can try another tool like https://github.com/lossless1024/StreaMonitor or https://github.com/oliverjrose99/Recordurbate

Sure, my internet have 25MB/s download speed and an average of 67ms from Chaturbate server. Sad it have so much frame loss but thank u anyway, I'll try these other apps.
