### ISSUE TITLE
Program shows channel not online

### ISSUE THREAD

**Issue by R1ck-on** [teacat/chaturbate-dvr#16]
Program results as channel is not online however the user is online.

**Comment by YamiOdymel** [comment]
What command do you use to run the program 🤔?

**Comment by R1ck-on** [comment]
chaturbate-dvr -u channelname -s 500

Used above command in terminal in windows 64

**Comment by YamiOdymel** [comment]
hmmmm weird, maybe it's a private stream which the program is not supported?

**Comment by R1ck-on** [comment]
Not exactly, cus I understand that private stream in chaturbate is not visible for all. so that could be an issue if the program was looking for the channel the same time as they went for a private show.. But i tried with multiple channels still getting "channelname is not online, checking again after 1 minute(s)..." as response. 

Is there a specific format in which I have to enter channel name to the program. Eg, if channel name is x_y_z, I enter command as, chaturbate-dvr -u x_y_z -s 500.. Am I doing it right??

**Comment by YamiOdymel** [comment]
I downloaded the latest version (0.7.0) and tried a random channel it seems to be fine, not sure what went wrong 🫠

![image](https://user-images.githubusercontent.com/7308718/192133345-92872832-8c0a-45cf-83b4-4a425221a6ec.png)

**Comment by YamiOdymel** [comment]
The channel name is the one you can see from the URL (`innocentprovenguilty` for example), so I think you are not mistaken

![image](https://user-images.githubusercontent.com/7308718/192133466-b678e44f-43de-49c2-9bca-5f7768e90797.png)

**Comment by R1ck-on** [comment]
ya, I tried the same channel u did but same result with and without vpn

![image](https://user-images.githubusercontent.com/114253170/192134046-f127bdb4-3b1a-4694-851f-7397e3ace0f7.png)

anyway I'll try the other programs suggested. Thanks..!!
