### ISSUE TITLE
download, chunk

### ISSUE THREAD

**Issue by 65654865** [teacat/chaturbate-dvr#17]
Almost perfect, but i set the strip value as 9000 but still spilt at around 3000Mb, 
and dose it set as default to preserve vedio segments? many segments left undeleted which i rather not to keep

**Comment by YamiOdymel** [comment]
Hmmm, it's weird, do you see the `specifying stripping limit as 9000 MiB(s)` information text when you starting up the program?

The default value is `0` so it shouldn't be `3000`, one possibility is that the stream source was cutted into 3,000 MB as a chunk but who knows.

The undeleted segments are still a bug waiting to be fixed, I aiming to make a beautiful Web UI and refactor the whole program to fix that problem, just not sure when :(
