### ISSUE TITLE
是不是墙内用不了

### ISSUE THREAD

**Issue by gupengzytm** [teacat/chaturbate-dvr#19]
你好，台湾的老哥
我开VPN，它也一直显示Not online。
是不是我在墙内的原因

**Comment by YamiOdymel** [comment]
如果你可以上 Chaturbate 那照理來說應該沒問題

會不會是你用 -u 參數指名的時候，打錯了頻道名稱 🤔

**Comment by gupengzytm** [comment]
-u 后面的加/  / 中间的，我试了好几个都不行，我ping了下CB也ping不通，但是网页能打开，应该是我电脑或者系统的问题。
谢谢老哥了
