### ISSUE TITLE
not working idk

### ISSUE THREAD

**Issue by nsa5574** [teacat/chaturbate-dvr#21]
I am not an expert in coding, i execute the program with the username it loads for like 10sec then it show me this: 

---
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xd6dd0a]

goroutine 1 [running]:
main.getBody({0xc00000e0e0, 0x9})
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:82 +0xaa
main.getOnlineStatus({0xc00000e0e0?, 0xe06ced?})
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:90 +0x1e
main.endpoint(0xc00005a180?)
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:331 +0x54a
github.com/urfave/cli/v2.(*App).RunContext(0xc0000436c0, {0xeb0430?, 0xc00000e110}, {0xc000024080, 0x3, 0x4})
        /mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
        /mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:371 +0x3eb

idk if I downloaded it incorrectly, but here is what i did, i downloaded it as a zip file, extracted it, then went to the path of the bin file and executed the program with the username | chaturbate-dvr.exe -u [i put the name] 

did i do anything incorrectly?

**Comment by YamiOdymel** [comment]
![image](https://user-images.githubusercontent.com/7308718/207730825-e33b045d-5c18-47cb-b3c1-6418e800d539.png)


```
chaturbate-dvr.exe -u channel_name_here
````

I think the command you executed is correct, but the error shouldn't occurred at that line of code. 

What happen if you run the program again? Is your network stable? 🤔

**Comment by nsa5574** [comment]
yes network is stable should i redownload it?

**Comment by YamiOdymel** [comment]
Maybe try to download it again from the Release (https://github.com/teacat/chaturbate-dvr/releases/tag/v0.8-alpha).

![image](https://user-images.githubusercontent.com/7308718/207731074-d115685e-70b5-4951-9c68-9266398a3b78.png)

Click on the "Source code (zip)" and grab the `/bin/windows/chaturbate.exe` and execute.

**Comment by YamiOdymel** [comment]
The error occurred on the line of code where the program trying to get the Website Content.

Maybe your Firewall or Windows Defender (the builtin Antivirus software) blocked it, 

but it doesn't happen on my computer though 🤔🤔

**Comment by nsa5574** [comment]
i will see

**Comment by nsa5574** [comment]
btw still same thing happened

**Comment by YamiOdymel** [comment]
Mind to provide the channel name? Some channels are weird-

**Comment by nsa5574** [comment]
its not the firewall i just turned off everything still same thing idk

**Comment by nsa5574** [comment]
is your computer firewall on?

**Comment by YamiOdymel** [comment]
Yea, mine firewall and antivirus are all on. What's the channel name you are trying to use with `chaturbate-dvr`?

**Comment by nsa5574** [comment]
anabella_stone

**Comment by YamiOdymel** [comment]
If the problem still occurred, maybe check https://github.com/lossless1024/StreaMonitor or https://github.com/oliverjrose99/Recordurbate if it will work for you 😭

**Comment by YamiOdymel** [comment]
> anabella_stone

It works fine on my computer, can't really reproduce the error, sadly.

**Comment by nsa5574** [comment]
i have a qs

**Comment by nsa5574** [comment]
when getting the file path do i put the program with path or like the path where exe file is

**Comment by YamiOdymel** [comment]
> when getting the file path do i put the program with path or like the path where exe file is

I don't understand the question. You can put the `chaturbate-dvr.exe` anywhere. if you put it in `/Downloads` then just go `/Downloads` and execute `chaturbate-dvr.exe -u channel_name`

> acc nvm, do i run cmd as admin?

I don't think it's required, but you can try.

**Comment by YamiOdymel** [comment]
or maybe if- a system reboot will fix it? 👀

**Comment by nsa5574** [comment]
nope, I guess it will never work for me, anyways thanks for the help, i will try that now
