### ISSUE TITLE
房間名中間包含“_”字符時會報錯

### ISSUE THREAD

**Issue by hbdjks** [teacat/chaturbate-dvr#22]
比如房間為Regina_Bigass，單詞中間由"_"字符連接，運行時會出現：
runtime error: invalid memory address or nil pointer dereference

**Comment by YamiOdymel** [comment]
![image](https://user-images.githubusercontent.com/7308718/208726767-1b15e263-2568-48a9-9710-191719e6e6b0.png)

我這邊執行 `chaturbate -u seltin_sweety` 的時候不會發生錯誤，你的整體錯誤訊息（有一堆路徑）的那些一起貼上來看看。

前幾天也有人出現類似的錯誤 #21 但不知道是什麼原因

**Comment by YamiOdymel** [comment]
下載最新的 [chaturbate.exe (https://github.com/teacat/chaturbate-dvr/raw/b7a7f11c6836d1469c123c022cc6a78052fbdc60/bin/windows/chaturbate-dvr.exe)](https://github.com/teacat/chaturbate-dvr/raw/b7a7f11c6836d1469c123c022cc6a78052fbdc60/bin/windows/chaturbate-dvr.exe) 試試看，這會輸出一些錯誤訊息，再試著把整個訊息貼上來看看。

**Comment by hbdjks** [comment]
下載了最新的程序后嘗試了很多房間，會出現這樣的錯誤，但是多試幾次就可以正常保存視頻了，之前發生錯誤時記得好像沒有那三行紅色的字
![2022-12-21 (1)](https://user-images.githubusercontent.com/62651446/208808037-95129d7c-c391-4576-841f-43e4f4374e55.png)

**Comment by hbdjks** [comment]
使用0.8 Alpha的Source code壓縮包裏的文件就會出現這樣的問題：
![2022-12-21 (2)](https://user-images.githubusercontent.com/62651446/208808944-9986d835-31c0-42f6-9acd-93bc93e39a46.png)

**Comment by YamiOdymel** [comment]
那段紅色的錯誤表示你的電腦連線到 Chaturbate 伺服器取得影片清單的時候，
被 Chaturbate 的伺服器中斷了。

目前還不確定什麼原因，
但也有可能跟你的網路供應商或地區問題有關係，我還沒什麼頭緒該如何解決。

你看 Chaturbate 網頁可能是正常的。也許 Chaturbate 的網頁有自己的備用方案，
但我還沒研究他們的備用方案是怎麼實作的 🤔

**Comment by hbdjks** [comment]
是的，紅色錯誤是網絡問題，是隨機出現的，我多嘗試幾次就好了，使用最新的程序目前就可以正常保存視頻了，應該是0.8 Alpha裏的程序有些問題

**Comment by YamiOdymel** [comment]
我覺得那比較像運氣或是網路剛好卡到的問題，

我只是把原本的 0.8 Alpha 程式加上出錯的時候輸出錯誤訊息，

還是想不太出來為什麼會發生這個問題，等到有更多錯誤特徵的時候再來研究 🫠

**Comment by hbdjks** [comment]
嗯嗯，好的，謝謝，不好意思麻煩您了
