### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by renzzla** [teacat/chaturbate-dvr#25]
Thanks for the great little script, it really helps.

I was running it recently, and it had been monitoring a performer for around a couple of days, but it then crashed. The log shows

> 2023/03/08 11:38:56 [37m[INFO] iris_diaz is not online, check again in 1 minute(s)[0m
> 2023/03/08 11:39:57 [37m[INFO] iris_diaz is not online, check again in 1 minute(s)[0m
> 2023/03/08 11:40:57 [37m[INFO] iris_diaz is not online, check again in 1 minute(s)[0m
> 2023/03/08 11:41:58 [37m[INFO] iris_diaz is not online, check again in 1 minute(s)[0m
> 2023/03/08 11:42:58 [37m[INFO] iris_diaz is not online, check again in 1 minute(s)[0m
> 2023/03/08 11:43:58 [37m[INFO] iris_diaz is not online, check again in 1 minute(s)[0m
> 2023/03/08 11:45:16 [31mGet "https://chaturbate.com/iris_diaz/": read tcp 46.232.211.100:5676->104.18.100.40:443: read: connection reset by peer[0m
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x727097]
> 
> goroutine 1 [running]:
> main.getBody({0x7fff58557794, 0x9})
> 	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:86 +0x377
> main.getOnlineStatus({0x7fff58557794?, 0x7bf261?})
> 	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:94 +0x1e
> main.endpoint(0xc0000f82a0?)
> 	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:351 +0x54a
> github.com/urfave/cli/v2.(*App).RunContext(0xc0001ca4e0, {0x864dd0?, 0xc00001a0c0}, {0xc000016180, 0x3, 0x3})
> 	/mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c
> github.com/urfave/cli/v2.(*App).Run(...)
> 	/mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
> main.main()
> 	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:391 +0x3eb
> 

I guess the "connection reset by peer" is causing this?

Thanks

**Comment by YamiOdymel** [comment]
Fixed, please try with the latest `/bin` files or download from https://github.com/teacat/chaturbate-dvr/releases/tag/v0.91-alpha version

Chaturbate has a bad- network connection 🥺

Normally the program retries if can't receive a successful response, but this situation is more like an underlying (low-level) network error that a "response" doesn't even exist, so checking something doesn't _exist_ it panics.
