### ISSUE TITLE
V 0.91 crash

### ISSUE THREAD

**Issue by renzzla** [teacat/chaturbate-dvr#26]
Just a short while after installing 0.91, it failed while recording an active stream:

> 2023/03/09 14:51:14 [32m[INFO] inserting 1734 segment to the master file. [total: 1735][0m
2023/03/09 14:51:17 fetching media_w567023182_b5128000_t64RlBTOjMwLjA=_1767.ts (size: 887924)
2023/03/09 14:51:17 fetching media_w567023182_b5128000_t64RlBTOjMwLjA=_1768.ts (size: 984744)
2023/03/09 14:51:18 [32m[INFO] inserting 1735 segment to the master file. [total: 1737][0m
2023/03/09 14:51:18 [32m[INFO] inserting 1736 segment to the master file. [total: 1737][0m
2023/03/09 14:51:19 fetching media_w567023182_b5128000_t64RlBTOjMwLjA=_1769.ts (size: 1077616)
2023/03/09 14:51:20 [32m[INFO] inserting 1737 segment to the master file. [total: 1738][0m
2023/03/09 14:51:21 fetching media_w567023182_b5128000_t64RlBTOjMwLjA=_1770.ts (size: 1021028)
2023/03/09 14:51:21 fetching media_w567023182_b5128000_t64RlBTOjMwLjA=_1771.ts (size: 1145296)
fatal error: concurrent map writes
fatal error: concurrent map writes
2023/03/09 14:51:22 [32m[INFO] inserting 1738 segment to the master file. [total: 1740][0m

goroutine 33699 [running]:
main.fetchSegment(0x0?, 0xc0001d2380, {0xc000450140, 0x89}, {0xc000134540, 0x1d}, 0xc0001c0240?)
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:313 +0x467
created by main.watchStream
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:231 +0x43e

goroutine 1 [chan receive]:
main.watchStream({0xc000370000, 0xbb}, {0x7ffd0e59e78b, 0x9}, 0xc0003b4058, {0xc000134540, 0x1d}, {0xc000450140, 0x89})
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:233 +0x46f
main.capture({0x7ffd0e59e78b, 0x9})
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:199 +0x2c5
main.endpoint(0xc0000f82a0?)
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:353 +0x5cb
github.com/urfave/cli/v2.(*App).RunContext(0xc0001c24e0, {0x864dd0?, 0xc00001a0c0}, {0xc000016180, 0x3, 0x3})
	/mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
	/mnt/c/Users/yamiodymel/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:391 +0x3eb

goroutine 414 [chan receive]:
main.combineSegment(0xc0003b4058, {0xc000134540, 0x1d})
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:258 +0x94
created by main.capture
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:198 +0x285

goroutine 33700 [running]:
	goroutine running on other thread; stack unavailable
created by main.watchStream
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:231 +0x43e

goroutine 33700 [running]:
main.fetchSegment(0xc00039c7d0?, 0xc0001d2400, {0xc000450140, 0x89}, {0xc000134540, 0x1d}, 0xc0001b0001?)
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:313 +0x467
created by main.watchStream
	/mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/main.go:231 +0x43e

**Comment by YamiOdymel** [comment]
Well- please try with the latest 0.92 Alpha (https://github.com/teacat/chaturbate-dvr/releases/tag/v0.92-alpha).

The program uses multi-threads to download the video segments, and there were multiple threads reading the buffer at the same time and it went boom, it's happened in very low chance and you get buy a lottery.

**Comment by renzzla** [comment]
Thanks again, I'll give it a try.
