### ISSUE TITLE
我出现了这样的错误该怎么办啊

### ISSUE THREAD

**Issue by NormanMises** [teacat/chaturbate-dvr#30]
我出现了这样的错误该怎么办啊
```
 Get "https://chaturbate.com/raquelle_star": dial tcp [2a03:2880:f11f:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Comment by YamiOdymel** [comment]
你的網路環境可能沒辦法安全地連線到 Chaturbate，

如果是在中國牆內的話 Chaturbate-DVR 本身不支援翻牆的功能

 #19

**Comment by NormanMises** [comment]
但是我使用了代理了呀 从网页是可以进去的 不过会有cloudflare验证

**Comment by NormanMises** [comment]
我用了这个[链接](https://github.com/Damianonymous/streamlink-plugins/issues/33)里的方法，但是仍出现了问题

**Comment by YamiOdymel** [comment]
有可能是網頁瀏覽器有成功使用代理伺服器，但程式、系統連網環境沒有透過代理？

這部份程式沒有辦法修正或改善，主要還是網路環境的問題

**Comment by NormanMises** [comment]
我估计也是😭 唉 太难了

**Comment by NormanMises** [comment]
老哥能不能加一个代理的选项呢？让软体走代理

**Comment by YamiOdymel** [comment]
電腦用 VPN 的時候，所有程式的網路都是透過 VPN 進出的，應該不用特別設計讓軟體走代理，

有可能是 不穩定的網路環境 + 程式爬取 而被 Cloudflare 視為 潛在危險 被擋下來，

Cloudflare 的用意本來就是為了阻擋機器人而設計的，程式沒有辦法繞過這個驗證

**Comment by NormanMises** [comment]
https://github.com/Anorov/cloudflare-scrape    记得好像有跳过cloudflare验证的库 似乎是这个
不过我用 的clash 好像并没走clash（即使开了全局

**Comment by YamiOdymel** [comment]
自 ([v2.0.1](https://github.com/teacat/chaturbate-dvr/releases/tag/v2.0.1)) 版本開始，可以透過環境變數 `HTTPS_PROXY` 變更 Chaturbate DVR 的代理方式

```bash
$ HTTPS_PROXY="socks5://127.0.0.1:9050" ./chaturbate-dvr -u CHANNEL_USERNAME
```

不確定是否有用，但還是提及一下
