### ISSUE TITLE
All models reported offline

### ISSUE THREAD

**Issue by renzzla** [teacat/chaturbate-dvr#31]
Something has changed over the past 24 hrs and now all models are being reported as offline when they are online. Any ideas on this? Thanks

2023/04/13 14:18:11 [37m[INFO] moorelina is not online, check again in 1 minute(s)[0m
2023/04/13 14:19:11 [37m[INFO] moorelina is not online, check again in 1 minute(s)[0m
2023/04/13 14:20:11 [37m[INFO] moorelina is not online, check again in 1 minute(s)[0m
2023/04/13 14:21:11 [37m[INFO] moorelina is not online, check again in 1 minute(s)[0m
2023/04/13 14:22:11 [37m[INFO] moorelina is not online, check again in 1 minute(s)[0m
2023/04/13 14:23:11 [37m[INFO] moorelina is not online, check again in 1 minute(s)[0m
2023/04/13 14:24:12 [37m[INFO] moorelina is not online, check again in 1 minute(s)[0m

**Comment by YamiOdymel** [comment]
![image](https://user-images.githubusercontent.com/7308718/231764905-906e3a64-547f-435e-b4d6-089081e70332.png)

Weird, it's working for me 🤔

**Comment by renzzla** [comment]
I had a few running so I killed them all and restarted and most are working. However there are the odd few thay aren't. Can you try this one?

2023/04/13 16:33:16 [37m[INFO] chanell6 is not online, check again in 1 minute(s)[0m
