### ISSUE TITLE
"An existing connection was forcibly closed by a remote host."

### ISSUE THREAD

**Issue by bilgla** [teacat/chaturbate-dvr#34]
![image](https://github.com/teacat/chaturbate-dvr/assets/145477334/8b61ca6b-5cc2-46a9-8433-2f153c1a194e)

"Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı." Means : "An existing connection was forcibly closed by a remote host."

I get this error when I send a command to a broadcast that I can open directly in the browser without using any vpn/dns in the browser. It was working fine before, but today when I changed my internet provider, I get this error.

**Comment by YamiOdymel** [comment]
"closed by a _remote host_" meaning the error was occurred because of "**remote host**".
There's nothing wrong with the application itself.

Sometimes it just- happened. Maybe their anti-bot detected it. Try to reboot the computer and see if it will work 
(I know it sounds stupid but it works somehow 🥲)

**Comment by YamiOdymel** [comment]
Some video websites using **P2P** or **WebRTC** to streaming video to your computer directly without middle Internet Provider after "First Handshake", so I will guess VPN helps your First Handshake. Once you handshaked with it, the rest video stream can be played without VPN, just my guess.

You will need VPN for your system to solve the problem, like SoftEther VPN, OpenVPN.

**Comment by bilgla** [comment]
Yes you are right. It works when we do "First Handshake", but when we
switch to private show and return, it asks for vpn again. Otherwise it
doesn't work, so I can't save what can be saved automatically. I guess I'll
have to use it like this. Thank you for your interest, sorry if I caused
any inconvenience.

Yami Odymel ***@***.***>, 29 Eyl 2023 Cum, 22:30 tarihinde
şunu yazdı:
