### ISSUE TITLE
Feature request : configure video quality 

### ISSUE THREAD

**Issue by Acenl12** [teacat/chaturbate-dvr#35]
I really appreciate the work you put in this and it's a great tool, especially being able to run it in docker.
But i notice the files get big very quickly.

Can you either provide an option in the tool to change the video quality, or provide quidance howto compress the file using ffmpeg for example.

**Comment by YamiOdymel** [comment]
I've updated the new version `0.94 Alpha` which adds 3 new arguments

```
--resolution 240, -r 240           Video resolution, could be 240, `480`, `540`, `720`, `1080` (default: "1080")
--resolution-fallback up, --rf up  Looking for larger or smaller resolution (up for larger, `down` for smaller) if a specified resolution was not found (default: "down")
--fps value, -f value              Preferred framerate, only works if steaming source supports it, otherwise it will always be 30 FPS (default: "60")
   ```
   
Now you can fetch the stream with a specified resolution:

```
$ ./chaturbate-dvr -u CHANNEL_NAME -r 300
```

It will looking for `300p` video resolution, depends on the value of `--resolution-fallback up/down`, the program will lookup for nearest resolution. Example output looks like this:

```
$ ./chaturbate-dvr -u CHANNEL_NAME -r 300

2023/10/01 18:37:51 Found available resolutions: 240, 480, 720, 1080
2023/10/01 18:37:51 Preferred video resolution 300p not found, use 240p instead.
2023/10/01 18:37:51 Fetching video in 30 FPS.
```

The [Dockerfile](https://github.com/teacat/chaturbate-dvr/blob/master/Dockerfile) is a bit too old, you might want to edit it yourself to support the new arguments (or send Pull Request to update it if you can). 

Remember to report the bugs if any error occurred.
