### ISSUE TITLE
Feature request: Record multiple streams 

### ISSUE THREAD

**Issue by Acenl12** [teacat/chaturbate-dvr#36]
Another feature request from my side:

With -u parameter, it looks you can only specify _one_ stream. I would like to have the ability to record multiple streams, maybe with a parameter like -i for input where you can specify a text file with the user names of multiple streams.

**Comment by YamiOdymel** [comment]
I was thinking the same but it increases the complexity so I'd like it to be as simple as possible.
(just like `ffmpeg` only does one task per program)

The current solution for multiple channels is to use Bash script or command line that execute multiple `chaturbate-dvr`.The program itself shouldn't cost too much performance, so it's fine to have multiple `chaturbate-dvr` opened.

Also the limitation seems to be watching 10 channels at the same time
(it was mentioned in #31)

I will leave the Issue opened but won't be implemented recently. 

---

duplicated #33
