### ISSUE TITLE
Feature request: H265

### ISSUE THREAD

**Issue by Acenl12** [teacat/chaturbate-dvr#37]
When I transcode the output files using ffmpeg with using h265 they get half the size. Is that something you can implement in your application logic?

```
For example file:1
Original File size: 259 MB
Size after ffmpeg H265: 120 MB
```

**Comment by YamiOdymel** [comment]
`chaturbate-dvr` is a simple program that combines stream clips into a single file. I don't have plans to implement real-time transcoding/encoding, as this would introduce additional dependencies on`ffmpeg` 🥲.

It's better to use `ffmpeg` on your own after the show, you can even do batch process if you [know how to command](https://stackoverflow.com/questions/5784661/how-do-you-convert-an-entire-directory-with-ffmpeg).
