### ISSUE TITLE
Channels who are online are reported as offline 

### ISSUE THREAD

**Issue by Acenl12** [teacat/chaturbate-dvr#38]
[INFO] channel is not online, check again in 1 minute(s)

Debian 12
V.0.94 @YamiOdymel

**Comment by Acenl12** [comment]
Still this issue also on Ubuntu anr Debian 11

**Comment by YamiOdymel** [comment]
![image](https://github.com/teacat/chaturbate-dvr/assets/7308718/d7aec5d5-247d-4bf4-88da-a8ced58f6875)

It still works for me, it's most likely an Internet Provider issue, or the Chaturbate is blocking the program with some Protection 
 rules that based on your internet environment.

There's nothing I can help you with, maybe try https://github.com/lossless1024/StreaMonitor

Also https://github.com/teacat/chaturbate-dvr/issues/31 is watching 10 streams at a time and had the same issue.
