### ISSUE TITLE
Feature request: parameter for max file size

### ISSUE THREAD

**Issue by CrawlerZ7** [teacat/chaturbate-dvr#39]
Hello,
I think it could be useful to have a parameter to limit max file size of recorded video. Or maybe also add parameter if user wants to create new video file after max_file_size is reached or just to stop recording. 

Regards :)

**Comment by CrawlerZ7** [comment]
The same thing can work for max duration of video

**Comment by YamiOdymel** [comment]
Duration is a good idea, but the program actually don't know the duration of the clips, hence why I make the filesize feature first.

**Comment by CrawlerZ7** [comment]
Maybe it can check the value of `recordStartTime() - nowTime()` (counting pause when author goes to private/offline)?

**Comment by YamiOdymel** [comment]
Sounds good enoguh for estimated time if the requirement was not asking for very precise
