### ISSUE TITLE
DockerBuild

### ISSUE THREAD

**Issue by gunter423** [teacat/chaturbate-dvr#4]
Can you do a version for docker version ?

**Comment by YamiOdymel** [comment]
It's been a while for me about how to make a Dockerfile. You are able to use the program directly from `/bins` without any extra installations.

**Comment by gunter423** [comment]
Yes i know ahah, maybe can i proposal a pull request with Dockerfile ?  🙂

**Comment by YamiOdymel** [comment]
aw sure, that will be great

**Comment by YamiOdymel** [comment]
Solved by #5
