### ISSUE TITLE
Refactor the whole thing so people can stop crying

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/chaturbate-dvr#42]
The current version is a very basic cli program with spaghetti code.

The new version will introduce a Web UI (WIP) with ability to watch multiple channels, and can still be used as non-UI cli program (if someone wants to use it with docker).

![sshot-2023-12-16-15](https://github.com/teacat/chaturbate-dvr/assets/7308718/0ac66bc7-fa93-484f-ac67-b4d08a644798)

The bottom left is a `<textarea>` for channel logs and update in real-time. 

No one knows when can this new version to be done but- hey, atleast it's possible. Expect to fix #40, #39, #36, the remaining Username/Password is not expected to be supported for now.

**Comment by dougK44883** [comment]
>so people can stop crying

Seems a bit rough.  Maybe look into this - [Disabling issues](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues)  
  As this is still an `alpha` program, we don't expect to be full of features and tweaks.

Me, I'm happy with the CLI (don't need no docker).  Knowing the progress, time|length would be a benefit, yes I can get that with a few clicks here and there.  Starting for a set duration would be a good idea.  I believe if unattended, theoretically it could record until disk space is exhausted if the channel continues for hours and hours....  A parameter for download path would just be _nice_.

Thank for chaturbat-dvr!  I appreciate the continued development!
