### ISSUE TITLE
Feature Request: Save chanels in webGUI

### ISSUE THREAD

**Issue by DikkeMoeders0** [teacat/chaturbate-dvr#44]
Maybe an option so it saves the created channels in the web ui to a channels.json file or a channels.db file wilth sqlite.

This would be great for people that want to run the exe just every time they want to record instead of running a whole command line bat script. also the webui gives you more overview for the created channels.

I tried some things with sqlite and json but i can't get it working great, maybe we can create something together?

Thanks

**Comment by YamiOdymel** [comment]
I had the same thought for this feature, I will add it.

Maybe save the current channel list into channels.json everytime a channel was created, and loads it when program started.

**Comment by DikkeMoeders0** [comment]
yeah i was trying to create exactly that, but i dont have alot of expierience in coding tbh, i know the basics and how functions and all work but i am not a software developer ;)

**Comment by YamiOdymel** [comment]
Added, check https://github.com/teacat/chaturbate-dvr/commit/12a27d11d5136703b64681c1e54abc72b29b72bc to see what code was changed if you are in interest.
