### ISSUE TITLE
Issue: Zero KB files

### ISSUE THREAD

**Issue by DikkeMoeders0** [teacat/chaturbate-dvr#45]

**Comment by DikkeMoeders0** [comment]
A fix for deleting or not making the 0kb files?

**Comment by YamiOdymel** [comment]
oh interesting, can you tell when does it create the 0kb files? when the progrom started with saved channels? I didn't notice this issue

**Comment by DikkeMoeders0** [comment]
As far as i see it is tripping in the begin of the recording, the first like 500ms are repeated constantly for 5 secs straight then it works. thats not a problem, could be encoding on my side. but when a channel goes private or whatever i is for a few sec generating 0kb files
![Screenshot 2024-02-03 131100](https://github.com/teacat/chaturbate-dvr/assets/141372982/ba8c08b5-583d-4965-8ae0-95385953dd87)
