### ISSUE TITLE
Please do not include binaries in repos, just provide build instructions. Use Releases for binaries.

### ISSUE THREAD

**Issue by playertoo** [teacat/chaturbate-dvr#54]
Please do not include binaries in repos, just provide build instructions.
* When checking out the repo, the binaries are wasting space being a binary-blob which cannot be diff'd by git. Please consider placing binaries in the GitHub's Releases.
* The binary for amd64 linux for v1.0.4 has [single finding](https://www.virustotal.com/gui/file/b732689ded6e75e777b8d02652e66fd500517cd7e0801397378b148571a1fefc) of a "trojan" by a scanner I've not heard of. But when I build from source on Debian with Go 1.21 from backports, the [build is clean](https://www.virustotal.com/gui/file/b6e96e41c4614010d84c395b3a67a139da6b6a0d01af6de97a088e7f2670956b). 

NOTE: I would be worthwhile To clean up the previous check-ins so the future checkout will not be burdened with binary blobs through v1.0.4, you'll likely have to due some pruning and such. Then again, you could leave it as-is and just not include binaries, as the project's release page has just the source code.

Here's what I did on my Debian to make it:

```
git clone https://github.com/teacat/chaturbate-dvr  # and wait a while due to binary blobs
sudo apt install -t bookworm-backports golang-go    # due to default golang is currently 1.19, we need 1.21 in backports
apt policy golang                                   # to see our golang release
cd chaturbate-dvr 
rm -rf bin                                          # remove existing binaries
                                                    # To set GOOS GOARCH, it's a quick 'uname' shell test for linux & macos
GOOS=linux GOARCH=amd64 go build -o chaturbrate-dvr # no need for me to put in the bin path.
```

For those looking to use this open source code, always read the source code. This `go.mod` uses well known Golang librarys directory from github.com and golang.org. If you get this code or binary elsewhere, you might get a little something undesirable. And always check a binary against [virustotal](https://virustotal.com/).

**Comment by YamiOdymel** [comment]
The [scanner result](https://www.virustotal.com/gui/file/b732689ded6e75e777b8d02652e66fd500517cd7e0801397378b148571a1fefc) you've linked (with my build) shows it was passed, perhaps it's just a temporary false warning.

![image](https://github.com/teacat/chaturbate-dvr/assets/7308718/742ed608-4aa1-4bf2-9c18-378c0f1348e3)

Though sometimes I use [`upx`](https://upx.github.io/) to compress the binaries which might be false positive, then I checked [README_DEV.md](https://github.com/teacat/chaturbate-dvr/blob/master/README_DEV.md) and realized that I hadn't used it for `chaturbate-dvr` 💀

But- yea, I shall move binaries to Release in the next update.
