### ISSUE TITLE
Interval -i setting

### ISSUE THREAD

**Issue by sandspik3** [teacat/chaturbate-dvr#55]
Any reason the -i option was removed or any chance it can be added back?
To prevent hammering protection, I set multiple rooms to 3 minutes.

Otherwise online rooms can appear offline.

BTW: Love the new web interface, and ability to add multiple rooms via comma separation.

Might be nice to be able to set the defaults for the web interface as well, 720p,30fps, custom naming, split size.

Overall, amazing work.  Thank you for your efforts.

**Comment by YamiOdymel** [comment]
Glad to see a positive comment 🥺

I thought no one needs it so I removed the `interval` flag. I will add it back, but I've been busy lately :(

Also the "default settings" is mentioned in the [Help](https://github.com/teacat/chaturbate-dvr?tab=readme-ov-file#help) section.

> When runs in Web UI mode, the settings will be default settings for Web UI to create channels.

Well, I hope it's working.

**Comment by ericruas** [comment]
+1 to the request of adding back the interval option please

**Comment by YamiOdymel** [comment]
@ericruas It's been added back in [v1.0.5](https://github.com/teacat/chaturbate-dvr/releases/tag/v1.0.5)
which you can start the program with `-i` flag.

Example:

```
$ chaturbate-dvr -interval 3
```

and all channel being created in Web UI will have 3 minutes interval.

**Comment by ericruas** [comment]
@YamiOdymel it doesn't seem to be working when I run the command from the binary from release 1.0.5.

For example, if I run:

`x64_windows_chaturbate-dvr.exe -i 3`

I need the log message that it will check 1 minute later. And from the subsequent logs with timestamps, it does indeed check 1 minute later.

**Comment by YamiOdymel** [comment]
@ericruas Remove the `chaturbate_channels.json` and restart the program, 
or remove the existed channel and recreate again

**Comment by ericruas** [comment]
@YamiOdymel you got it! It's working now, I appreciate the guidance
