### ISSUE TITLE
App occasionally fails to detect online channel

### ISSUE THREAD

**Issue by arealusername** [teacat/chaturbate-dvr#56]
Sometimes the app does not detect that a channel is online and it says it is offline when it actually isn't. Are you aware of this happening, and is there already a way to force a retry built-in? Restarting the app does not fix the issue

**Comment by YamiOdymel** [comment]
Are you using any VPN? Which country you live in?

**Comment by arealusername** [comment]
No VPN and I am in the US

**Comment by YamiOdymel** [comment]
may related #61
