### ISSUE TITLE
The recorded video pauses every one minute

### ISSUE THREAD

**Issue by shofotolavski** [teacat/chaturbate-dvr#64]
The recorded video pauses every one minute

**Comment by YamiOdymel** [comment]
I just tested two channels and couldn't reproduce the issue; it might be a networking problem.

Which country do you live in? And when you say 'pauses every minute,' how long does it pause for?

**Comment by shofotolavski** [comment]
> 我刚刚测试了两个渠道，无法重现该问题；这可能是网络问题。
> 
> 您住在哪个国家？您说“每分钟暂停一次”，是指暂停多长时间？

The video will pause every one minute or so and then continue. I use VPN, but it works fine when I use another recording software that calls yt-dlp. I guess it uses ffmpeg to encode and generate mp4 files after the recording is completed, so there will be no such problem. I also tried a third software, which also generates .ts files and also has the problem of recording lag, so I guess it has something to do with ffmpeg.

**Comment by shofotolavski** [comment]
The video will pause every one minute or so and then continue. I use VPN, but it works fine when I use another recording software that calls yt-dlp. I guess it uses ffmpeg to encode and generate mp4 files after the recording is completed, so there will be no such problem. I also tried a third software, which also generates .ts files and also has the problem of recording lag, so I guess it has something to do with ffmpeg.

**Comment by shofotolavski** [comment]
After testing I solved this problem, the reason was that ffmpeg was not set up correctly, thank you

**Comment by YamiOdymel** [comment]
oh great, glad to know it's not a chaturbate-dvr issue
