### ISSUE TITLE
 segment not found in buffer, skipped

### ISSUE THREAD

**Issue by shofotolavski** [teacat/chaturbate-dvr#65]
“2024-08-11 10:40:40] [WARN] segment #3226 not found in buffer, skipped”

This message will appear after a few seconds at random.

**Comment by YamiOdymel** [comment]
It's a warning due to bad network environment.

The video it fetched may lost some framerate but it's not a program issue so you can ignore it.

**Comment by shofotolavski** [comment]
> It's a warning due to bad network environment.
> 
> The video it fetched may lost some framerate but it's not a program issue so you can ignore it.

Can I solve this problem by setting a larger cache? How can I do this?

**Comment by YamiOdymel** [comment]
"Buffer" might not be the best term when I named it.

As each "segment" has a time limit. Once it expires, it cannot be retrieved again. 

Your issue is that the program is unable to obtain the segment before it expires, so it has to give up trying.

There is no "actual cache" that can be set to be large 🥲

**Comment by shofotolavski** [comment]
> "Buffer" might not be the best term when I named it.
> 
> As each "segment" has a time limit. Once it expires, it cannot be retrieved again.
> 
> Your issue is that the program is unable to obtain the segment before it expires, so it has to give up trying.
> 
> There is no "actual cache" that can be set to be large 🥲

All the software I have used that uses the .ts format have this problem. If there is a network buffer, maybe it can be solved, or if other formats are used?

**Comment by YamiOdymel** [comment]
The "buffer" **only** exists on the server side, which you cannot control.

Because they are a streaming website, not YouTube, they don't store videos permanently, so the segments are always deleted after a time limit set by the website.
