### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by PixelByte1** [teacat/chaturbate-dvr#66]
Hello,

I get the following error message every 1-2 days, the more streams I record, the more often the error message appears.

fatal error: concurrent map read and map write

goroutine 132669 [running]:
github.com/teacat/chaturbate-dvr/chaturbate.(*Channel).mergeSegments(0x400048cf20)
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/channel_internal.go:218 +0xa0
created by github.com/teacat/chaturbate-dvr/chaturbate.(*Channel).record in goroutine 31
        /mnt/c/Users/yamiodymel/go/src/github.com/teacat/chaturbate-dvr/chaturbate/channel_internal.go:58 +0x1dc
[...]

Thanks for your help in advance!

**Comment by YamiOdymel** [comment]
Please try v1.0.6, should fixed the issue
https://github.com/teacat/chaturbate-dvr/releases/tag/v1.0.6
